# Jekyll settings
theme: jekyll-theme-slate

# Website values
title: Title # (optional) use for events list title or organization name
description: Organization name # (optional) use for events list title or organization name

# Eventshaper data
hash:
