# Jekyll settings
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
    values:
      layout: base # Comment out this to see how gem template default.html layout looks (works only with README.md)

# Website values
use_header: True # title & description displayed
title: Konferencje dla lekarzy # (optional) use for events list title or organization name
description: C&P Pharma # (optional) use for events list title or organization name
footer_content: # Add footer data if needed

# Eventshaper data
domain: https://eventshaper.pl
hash: 9hyyv8bmuhh59xtj
locale: pl
