# Jekyll settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: base # Comment out this to see how gem template default.html layout looks (works only with README.md)

copyright:
  year:             2017
  name:             C&P Pharma Solution
  url:              http://cp-pharma.pl

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Google-analytics
google-analytics:
  id:               ""

# Website values
use_header: True # title & description displayed
title: Warsztaty praktyczne dla Lekarzy # (optional) use for events list title or organization name
description: C&P Pharma Solution # (optional) use for events list title or organization name

# Eventshaper data
domain: https://eventshaper.pl
hash: 9hyyv8bmuhh59xtj
locale: pl